Created by Thai Vang and Navpreet Kloy

Dataset from: https://www.kaggle.com/datasets/ttv9129/gamestore-dataset

In [ ]:
#Adding code to get rid of deprecation warning due to outdated imports.
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [ ]:
# call the required libraries
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
#Importing dataset into colab
df=pd.read_csv('gamestore.csv')
df.head()

  Game Pass,Game,Batteries,Gift Card
0          Game,Controller,Gift Card
1                               Game
2             Game,Headset,Game Pass
3        Batteries,Headset,Game Pass
4                            Console

In [ ]:
#Adding prodcut as column header
df=pd.read_csv('gamestore.csv', names=['Product'])
df.head()

                              Product
0  Game Pass,Game,Batteries,Gift Card
1           Game,Controller,Gift Card
2                                Game
3              Game,Headset,Game Pass
4         Batteries,Headset,Game Pass

In [ ]:
#Code to show shape of the dataset showing 400 rows with one column
df.shape

(400, 1)

In [ ]:
#converting pandas dataframe into a list of lists
data=list(df["Product"].apply(lambda x:x.split(",")))
data

[['Game Pass', 'Game', 'Batteries', 'Gift Card'],
 ['Game', 'Controller', 'Gift Card'],
 ['Game'],
 ['Game', 'Headset', 'Game Pass'],
 ['Batteries', 'Headset', 'Game Pass'],
 ['Console'],
 ['Game Pass'],
 ['Game Pass', 'Batteries', 'Headset'],
 ['Game Pass', 'Console', 'Gift Card'],
 ['Batteries', 'Game Pass'],
 ['Controller', 'Game Pass', 'Batteries'],
 ['Game Pass', 'Console', 'Game'],
 ['Headset', 'Gift Card', 'Game', 'Console'],
 ['Game Pass', 'Game', 'Gift Card'],
 ['Batteries', 'Gift Card'],
 ['Gift Card', 'Batteries', 'Controller'],
 ['Gift Card', 'Controller', 'Console'],
 ['Controller'],
 ['Game', 'Batteries', 'Gift Card', 'Console'],
 ['Headset', 'Console'],
 ['Batteries', 'Game', 'Controller', 'Gift Card'],
 ['Game'],
 ['Controller'],
 ['Game Pass'],
 ['Batteries', 'Gift Card', 'Controller'],
 ['Game'],
 ['Headset', 'Game Pass', 'Controller', 'Game'],
 ['Headset', 'Game', 'Gift Card', 'Console'],
 ['Console', 'Gift Card'],
 ['Gift Card', 'Headset', 'Batteries'],
 ['Console', 'Controller', 'Gift Card'],
 ['Game'],
 ['Game', 'Gift Card'],
 ['Batteries', 'Controller', 'Console', 'Headset'],
 ['Headset', 'Gift Card', 'Game Pass', 'Controller'],
 ['Game', 'Game Pass'],
 ['Console'],
 ['Controller', 'Game', 'Gift Card', 'Console'],
 ['Game', 'Game Pass', 'Headset'],
 ['Console', 'Game Pass', 'Game', 'Headset'],
 ['Batteries', 'Gift Card', 'Headset', 'Controller'],
 ['Batteries'],
 ['Headset', 'Game'],
 ['Headset', 'Gift Card', 'Batteries'],
 ['Console'],
 ['Game', 'Controller'],
 ['Console', 'Controller', 'Headset'],
 ['Gift Card', 'Game Pass', 'Controller', 'Headset'],
 ['Console', 'Batteries', 'Game Pass'],
 ['Controller', 'Headset', 'Gift Card'],
 ['Game', 'Gift Card'],
 ['Game', 'Gift Card', 'Headset'],
 ['Headset', 'Game Pass'],
 ['Game Pass', 'Game', 'Batteries'],
 ['Console', 'Game', 'Batteries', 'Headset'],
 ['Game'],
 ['Game Pass'],
 ['Batteries', 'Gift Card'],
 ['Game', 'Controller'],
 ['Game', 'Console', 'Controller'],
 ['Console', 'Headset', 'Gift Card', 'Game'],
 ['Gift Card', 'Game Pass'],
 ['Batteries', 'Gift Card', 'Controller', 'Console'],
 ['Batteries', 'Headset', 'Gift Card'],
 ['Game Pass'],
 ['Game Pass'],
 ['Game Pass', 'Batteries', 'Console', 'Headset'],
 ['Console', 'Batteries', 'Gift Card', 'Controller'],
 ['Headset', 'Game'],
 ['Batteries'],
 ['Console', 'Batteries'],
 ['Headset', 'Controller', 'Game', 'Console'],
 ['Gift Card', 'Game'],
 ['Game', 'Controller', 'Batteries'],
 ['Headset', 'Game Pass', 'Controller'],
 ['Controller'],
 ['Game Pass', 'Batteries', 'Game', 'Controller'],
 ['Game', 'Headset'],
 ['Gift Card', 'Game', 'Game Pass', 'Controller'],
 ['Console', 'Headset'],
 ['Controller', 'Headset', 'Batteries', 'Gift Card'],
 ['Game', 'Console', 'Controller'],
 ['Batteries', 'Game Pass', 'Controller', 'Headset'],
 ['Headset', 'Gift Card'],
 ['Controller'],
 ['Console', 'Batteries'],
 ['Batteries', 'Console', 'Headset'],
 ['Batteries', 'Game Pass', 'Console'],
 ['Batteries', 'Headset', 'Gift Card', 'Controller'],
 ['Gift Card', 'Batteries', 'Game Pass'],
 ['Headset', 'Console', 'Gift Card'],
 ['Gift Card', 'Game Pass'],
 ['Batteries', 'Controller', 'Headset', 'Game'],
 ['Batteries', 'Console', 'Controller'],
 ['Console', 'Controller', 'Batteries', 'Headset'],
 ['Console'],
 ['Console', 'Batteries', 'Controller', 'Gift Card'],
 ['Game Pass', 'Game'],
 ['Console'],
 ['Batteries', 'Gift Card'],
 ['Batteries'],
 ['Batteries', 'Headset', 'Game', 'Gift Card'],
 ['Game', 'Console', 'Batteries', 'Headset'],
 ['Game', 'Controller', 'Headset', 'Game Pass'],
 ['Gift Card', 'Batteries', 'Game Pass', 'Controller'],
 ['Game Pass', 'Headset', 'Console', 'Gift Card'],
 ['Gift Card', 'Controller', 'Game Pass'],
 ['Console', 'Game', 'Controller', 'Gift Card'],
 ['Game'],
 ['Game', 'Controller'],
 ['Game', 'Controller', 'Game Pass', 'Batteries'],
 ['Controller', 'Batteries', 'Game'],
 ['Game'],
 ['Gift Card', 'Console'],
 ['Gift Card'],
 ['Controller', 'Console', 'Gift Card'],
 ['Gift Card', 'Game', 'Game Pass', 'Batteries'],
 ['Gift Card', 'Batteries'],
 ['Game', 'Game Pass'],
 ['Game', 'Game Pass'],
 ['Headset', 'Controller', 'Game'],
 ['Controller'],
 ['Console', 'Headset', 'Gift Card'],
 ['Game', 'Gift Card', 'Batteries'],
 ['Game Pass', 'Batteries', 'Gift Card', 'Console'],
 ['Console', 'Headset', 'Game', 'Batteries'],
 ['Game'],
 ['Game Pass', 'Console'],
 ['Headset', 'Game'],
 ['Game Pass', 'Controller', 'Headset'],
 ['Game Pass', 'Gift Card', 'Console', 'Headset'],
 ['Headset', 'Game Pass', 'Console', 'Gift Card'],
 ['Batteries', 'Controller', 'Console'],
 ['Console'],
 ['Console'],
 ['Headset', 'Game Pass'],
 ['Headset', 'Console'],
 ['Controller', 'Game Pass', 'Headset', 'Game'],
 ['Headset', 'Gift Card'],
 ['Controller', 'Batteries', 'Headset', 'Console'],
 ['Controller', 'Headset'],
 ['Gift Card'],
 ['Headset'],
 ['Controller'],
 ['Batteries', 'Game Pass', 'Gift Card', 'Headset'],
 ['Batteries'],
 ['Controller'],
 ['Batteries', 'Gift Card', 'Headset'],
 ['Game Pass'],
 ['Controller'],
 ['Game'],
 ['Controller'],
 ['Gift Card'],
 ['Batteries', 'Gift Card', 'Headset'],
 ['Game Pass', 'Controller', 'Gift Card'],
 ['Game Pass', 'Headset'],
 ['Game', 'Batteries', 'Gift Card'],
 ['Game Pass'],
 ['Game Pass', 'Game', 'Batteries'],
 ['Headset', 'Controller', 'Console'],
 ['Game'],
 ['Gift Card'],
 ['Headset'],
 ['Headset', 'Console'],
 ['Batteries', 'Game', 'Headset', 'Game Pass'],
 ['Batteries'],
 ['Gift Card', 'Batteries', 'Headset'],
 ['Console'],
 ['Batteries', 'Headset', 'Gift Card', 'Controller'],
 ['Headset', 'Console', 'Batteries'],
 ['Batteries', 'Gift Card', 'Game Pass'],
 ['Gift Card'],
 ['Gift Card', 'Headset', 'Batteries'],
 ['Headset', 'Game'],
 ['Controller'],
 ['Gift Card', 'Console'],
 ['Game Pass'],
 ['Console', 'Game'],
 ['Game Pass'],
 ['Controller'],
 ['Batteries', 'Console', 'Headset', 'Gift Card'],
 ['Batteries', 'Game', 'Controller'],
 ['Gift Card', 'Batteries'],
 ['Headset', 'Controller', 'Batteries', 'Game Pass'],
 ['Console', 'Batteries'],
 ['Controller'],
 ['Game Pass'],
 ['Headset', 'Console', 'Batteries', 'Gift Card'],
 ['Headset', 'Game Pass'],
 ['Game Pass', 'Controller'],
 ['Gift Card', 'Console', 'Batteries'],
 ['Game'],
 ['Console'],
 ['Gift Card', 'Console'],
 ['Batteries'],
 ['Gift Card'],
 ['Game'],
 ['Batteries'],
 ['Controller', 'Gift Card', 'Headset', 'Console'],
 ['Console', 'Batteries', 'Controller', 'Gift Card'],
 ['Console', 'Batteries', 'Game Pass'],
 ['Controller', 'Game', 'Headset', 'Console'],
 ['Gift Card', 'Console'],
 ['Game Pass', 'Headset', 'Batteries', 'Console'],
 ['Gift Card', 'Game'],
 ['Game', 'Game Pass'],
 ['Game', 'Batteries', 'Gift Card'],
 ['Batteries'],
 ['Game Pass'],
 ['Gift Card', 'Game Pass'],
 ['Game', 'Batteries', 'Headset'],
 ['Game Pass'],
 ['Console', 'Game Pass', 'Game'],
 ['Headset', 'Game'],
 ['Game Pass', 'Headset', 'Gift Card', 'Batteries'],
 ['Console', 'Controller', 'Headset'],
 ['Console'],
 ['Game', 'Batteries'],
 ['Gift Card', 'Batteries', 'Game Pass'],
 ['Console', 'Gift Card'],
 ['Controller', 'Batteries'],
 ['Headset', 'Game', 'Game Pass'],
 ['Game Pass'],
 ['Game'],
 ['Controller', 'Headset', 'Game', 'Game Pass'],
 ['Gift Card', 'Game Pass', 'Headset', 'Game'],
 ['Game Pass', 'Controller', 'Console', 'Headset'],
 ['Gift Card', 'Controller', 'Console', 'Batteries'],
 ['Controller', 'Console', 'Gift Card'],
 ['Console', 'Controller'],
 ['Gift Card'],
 ['Headset', 'Batteries'],
 ['Gift Card'],
 ['Game', 'Headset', 'Console', 'Controller'],
 ['Gift Card', 'Game'],
 ['Console', 'Batteries'],
 ['Batteries', 'Headset', 'Controller', 'Game'],
 ['Game Pass', 'Gift Card', 'Headset', 'Game'],
 ['Controller', 'Console', 'Gift Card'],
 ['Game Pass', 'Game'],
 ['Gift Card', 'Controller', 'Game', 'Batteries'],
 ['Console', 'Gift Card', 'Batteries', 'Controller'],
 ['Game', 'Gift Card'],
 ['Game Pass', 'Controller'],
 ['Console', 'Controller', 'Headset'],
 ['Gift Card', 'Console', 'Game Pass'],
 ['Console', 'Headset', 'Game'],
 ['Gift Card', 'Console', 'Game'],
 ['Gift Card'],
 ['Headset', 'Console', 'Game'],
 ['Batteries'],
 ['Game Pass', 'Gift Card', 'Console'],
 ['Batteries', 'Game Pass'],
 ['Console', 'Batteries', 'Gift Card'],
 ['Console'],
 ['Batteries', 'Console', 'Gift Card'],
 ['Gift Card', 'Game', 'Controller', 'Batteries'],
 ['Controller', 'Batteries', 'Game'],
 ['Controller'],
 ['Gift Card', 'Headset', 'Controller'],
 ['Batteries', 'Gift Card'],
 ['Controller', 'Game Pass', 'Console'],
 ['Batteries', 'Game Pass'],
 ['Batteries', 'Headset', 'Gift Card'],
 ['Game Pass'],
 ['Game Pass', 'Console', 'Gift Card'],
 ['Batteries', 'Headset'],
 ['Game', 'Batteries', 'Console'],
 ['Headset', 'Batteries', 'Controller'],
 ['Console', 'Controller', 'Game', 'Game Pass'],
 ['Headset'],
 ['Game', 'Batteries', 'Gift Card'],
 ['Game Pass'],
 ['Game Pass', 'Batteries', 'Game', 'Controller'],
 ['Batteries'],
 ['Headset', 'Console', 'Controller'],
 ['Console'],
 ['Gift Card', 'Controller'],
 ['Gift Card', 'Controller'],
 ['Console', 'Game Pass', 'Game', 'Headset'],
 ['Controller'],
 ['Headset', 'Gift Card'],
 ['Headset', 'Console', 'Batteries', 'Gift Card'],
 ['Gift Card'],
 ['Controller', 'Gift Card', 'Game Pass'],
 ['Gift Card', 'Headset', 'Game', 'Console'],
 ['Controller', 'Console'],
 ['Batteries', 'Game', 'Console', 'Controller'],
 ['Game Pass', 'Game', 'Console', 'Controller'],
 ['Game Pass', 'Controller', 'Headset', 'Console'],
 ['Gift Card'],
 ['Batteries', 'Controller'],
 ['Batteries', 'Controller', 'Gift Card', 'Console'],
 ['Gift Card', 'Console', 'Game'],
 ['Headset', 'Game Pass'],
 ['Game'],
 ['Console', 'Headset', 'Game', 'Batteries'],
 ['Game Pass', 'Headset', 'Gift Card', 'Batteries'],
 ['Batteries', 'Gift Card', 'Controller'],
 ['Console', 'Controller', 'Game'],
 ['Game Pass', 'Controller', 'Console', 'Gift Card'],
 ['Console'],
 ['Batteries', 'Console', 'Controller', 'Headset'],
 ['Headset', 'Gift Card'],
 ['Batteries', 'Console', 'Controller', 'Game Pass'],
 ['Controller'],
 ['Game', 'Gift Card', 'Headset', 'Batteries'],
 ['Game', 'Headset'],
 ['Game', 'Controller', 'Headset'],
 ['Gift Card'],
 ['Controller', 'Gift Card', 'Game Pass', 'Headset'],
 ['Gift Card', 'Console', 'Batteries', 'Game'],
 ['Game Pass', 'Controller'],
 ['Batteries', 'Controller'],
 ['Batteries'],
 ['Game', 'Console'],
 ['Controller'],
 ['Gift Card', 'Headset'],
 ['Console', 'Controller', 'Batteries'],
 ['Game', 'Controller', 'Game Pass'],
 ['Gift Card', 'Game Pass'],
 ['Controller', 'Game', 'Batteries'],
 ['Console', 'Controller', 'Headset', 'Batteries'],
 ['Batteries', 'Console'],
 ['Controller', 'Game'],
 ['Controller'],
 ['Game', 'Controller', 'Console', 'Gift Card'],
 ['Batteries', 'Game Pass', 'Game', 'Headset'],
 ['Batteries', 'Game', 'Gift Card', 'Controller'],
 ['Controller'],
 ['Controller', 'Gift Card', 'Game Pass'],
 ['Game Pass', 'Game', 'Gift Card', 'Console'],
 ['Console', 'Headset'],
 ['Gift Card'],
 ['Controller', 'Gift Card', 'Batteries', 'Headset'],
 ['Game Pass', 'Gift Card'],
 ['Game Pass', 'Headset', 'Batteries'],
 ['Game'],
 ['Batteries', 'Game'],
 ['Game', 'Controller', 'Headset', 'Gift Card'],
 ['Console'],
 ['Console', 'Game'],
 ['Batteries'],
 ['Controller', 'Game Pass', 'Gift Card', 'Console'],
 ['Gift Card', 'Headset', 'Game Pass'],
 ['Game', 'Game Pass', 'Batteries'],
 ['Controller', 'Game'],
 ['Controller', 'Game Pass', 'Gift Card'],
 ['Batteries', 'Headset'],
 ['Headset', 'Batteries', 'Gift Card', 'Controller'],
 ['Console', 'Headset', 'Gift Card'],
 ['Gift Card', 'Game Pass', 'Console', 'Headset'],
 ['Game Pass', 'Game', 'Batteries'],
 ['Game', 'Gift Card', 'Headset'],
 ['Controller', 'Game', 'Console', 'Headset'],
 ['Game', 'Gift Card', 'Controller', 'Headset'],
 ['Controller'],
 ['Batteries', 'Gift Card', 'Game', 'Controller'],
 ['Game', 'Batteries', 'Gift Card', 'Console'],
 ['Gift Card', 'Game Pass', 'Batteries', 'Controller'],
 ['Console', 'Game Pass'],
 ['Controller'],
 ['Console'],
 ['Headset', 'Game Pass', 'Console', 'Controller'],
 ['Controller', 'Gift Card', 'Game'],
 ['Gift Card'],
 ['Headset'],
 ['Gift Card', 'Batteries', 'Game'],
 ['Game Pass', 'Headset'],
 ['Batteries', 'Game', 'Game Pass', 'Gift Card'],
 ['Batteries', 'Game'],
 ['Game', 'Controller'],
 ['Batteries', 'Game Pass', 'Controller'],
 ['Batteries', 'Game Pass'],
 ['Game Pass', 'Gift Card'],
 ['Game Pass', 'Batteries', 'Controller', 'Console'],
 ['Headset', 'Controller'],
 ['Gift Card', 'Console', 'Headset'],
 ['Game', 'Headset', 'Game Pass', 'Controller'],
 ['Gift Card'],
 ['Batteries'],
 ['Console', 'Controller', 'Game'],
 ['Controller', 'Batteries'],
 ['Headset'],
 ['Headset', 'Game Pass'],
 ['Console', 'Game'],
 ['Game Pass', 'Controller', 'Console', 'Game'],
 ['Console', 'Controller', 'Game'],
 ['Game Pass', 'Gift Card', 'Game', 'Headset'],
 ['Controller', 'Console'],
 ['Game', 'Game Pass'],
 ['Gift Card', 'Controller', 'Headset', 'Game'],
 ['Console', 'Batteries', 'Game Pass', 'Controller'],
 ['Console', 'Batteries', 'Controller', 'Gift Card'],
 ['Gift Card', 'Headset', 'Game'],
 ['Game Pass'],
 ['Game', 'Headset', 'Controller'],
 ['Gift Card', 'Console', 'Headset'],
 ['Console', 'Game Pass', 'Game', 'Controller'],
 ['Batteries', 'Game']]

In [ ]:
print(df.isnull().sum())  # Counts the number of missing (NaN) values in each column

Product    0
dtype: int64

In [ ]:
#transform the list with one-hot encoding
from mlxtend.preprocessing import TransactionEncoder
a=TransactionEncoder()
a_data=a.fit(data).transform(data)
df=pd.DataFrame(a_data, columns=a.columns_)

#Turn False & True to 0 and 1 for readability
df=df.replace(False,0)
df=df.replace(True,1)

df

/tmp/ipython-input-2362902784.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace(True,1)

     Batteries  Console  Controller  Game  Game Pass  Gift Card  Headset
0            1        0           0     1          1          1        0
1            0        0           1     1          0          1        0
2            0        0           0     1          0          0        0
3            0        0           0     1          1          0        1
4            1        0           0     0          1          0        1
..         ...      ...         ...   ...        ...        ...      ...
395          0        0           0     0          1          0        0
396          0        0           1     1          0          0        1
397          0        1           0     0          0          1        1
398          0        1           1     1          1          0        0
399          1        0           0     1          0          0        0

[400 rows x 7 columns]

In [ ]:
# SUPPORT threshold value
df=apriori(df,min_support=0.1,use_colnames=True)
df

    support                 itemsets
0    0.3650              (Batteries)
1    0.3525                (Console)
2    0.3775             (Controller)
3    0.3600                   (Game)
4    0.3225              (Game Pass)
5    0.3975              (Gift Card)
6    0.3450                (Headset)
7    0.1175     (Batteries, Console)
8    0.1375  (Batteries, Controller)
9    0.1125        (Batteries, Game)
10   0.1000   (Batteries, Game Pass)
11   0.1600   (Batteries, Gift Card)
12   0.1225     (Batteries, Headset)
13   0.1400    (Console, Controller)
14   0.1050          (Console, Game)
15   0.1375     (Console, Gift Card)
16   0.1275       (Console, Headset)
17   0.1325       (Game, Controller)
18   0.1050  (Controller, Game Pass)
19   0.1325  (Controller, Gift Card)
20   0.1225    (Controller, Headset)
21   0.1050        (Game, Game Pass)
22   0.1175        (Game, Gift Card)
23   0.1250          (Game, Headset)
24   0.1075   (Gift Card, Game Pass)
25   0.1125     (Headset, Game Pass)
26   0.1400     (Headset, Gift Card)

In [ ]:
#Using association_rules for the confidence parameter
df_ar=association_rules(df,metric="confidence", min_threshold=0.6)
df_ar

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [ ]:
#Here is the LIFT parameter.
df_ar=association_rules(df,metric="lift", min_threshold=1)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Batteries),(Gift Card),0.3650,0.3975,0.1600,0.438356,1.102783,1.0,0.014912,1.072744,0.146777,0.265560,0.067811,0.420436
1,(Gift Card),(Batteries),0.3975,0.3650,0.1600,0.402516,1.102783,1.0,0.014912,1.062789,0.154694,0.265560,0.059080,0.420436
2,(Console),(Controller),0.3525,0.3775,0.1400,0.397163,1.052088,1.0,0.006931,1.032618,0.076462,0.237288,0.031587,0.384012
3,(Controller),(Console),0.3775,0.3525,0.1400,0.370861,1.052088,1.0,0.006931,1.029184,0.079532,0.237288,0.028357,0.384012
4,(Console),(Headset),0.3525,0.3450,0.1275,0.361702,1.048412,1.0,0.005888,1.026167,0.071315,0.223684,0.025499,0.365634
5,(Headset),(Console),0.3450,0.3525,0.1275,0.369565,1.048412,1.0,0.005888,1.027069,0.070498,0.223684,0.026356,0.365634
6,(Game),(Headset),0.3600,0.3450,0.1250,0.347222,1.006441,1.0,0.000800,1.003404,0.010000,0.215517,0.003393,0.354771
7,(Headset),(Game),0.3450,0.3600,0.1250,0.362319,1.006441,1.0,0.000800,1.003636,0.009771,0.215517,0.003623,0.354771
8,(Headset),(Game Pass),0.3450,0.3225,0.1125,0.326087,1.011122,1.0,0.001238,1.005323,0.016794,0.202703,0.005294,0.337462
9,(Game Pass),(Headset),0.3225,0.3450,0.1125,0.348837,1.011122,1.0,0.001238,1.005893,0.016236,0.202703,0.005858,0.337462
10,(Headset),(Gift Card),0.3450,0.3975,0.1400,0.405797,1.020873,1.0,0.002863,1.013963,0.031216,0.232365,0.013771,0.378999
11,(Gift Card),(Headset),0.3975,0.3450,0.1400,0.352201,1.020873,1.0,0.002863,1.011117,0.033936,0.232365,0.010994,0.378999

In [ ]:
#Here is the CONVICTION parameter.
df_ar=association_rules(df,metric="conviction", min_threshold=1.0)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Batteries),(Gift Card),0.3650,0.3975,0.1600,0.438356,1.102783,1.0,0.014912,1.072744,0.146777,0.265560,0.067811,0.420436
1,(Gift Card),(Batteries),0.3975,0.3650,0.1600,0.402516,1.102783,1.0,0.014912,1.062789,0.154694,0.265560,0.059080,0.420436
2,(Console),(Controller),0.3525,0.3775,0.1400,0.397163,1.052088,1.0,0.006931,1.032618,0.076462,0.237288,0.031587,0.384012
3,(Controller),(Console),0.3775,0.3525,0.1400,0.370861,1.052088,1.0,0.006931,1.029184,0.079532,0.237288,0.028357,0.384012
4,(Console),(Headset),0.3525,0.3450,0.1275,0.361702,1.048412,1.0,0.005888,1.026167,0.071315,0.223684,0.025499,0.365634
5,(Headset),(Console),0.3450,0.3525,0.1275,0.369565,1.048412,1.0,0.005888,1.027069,0.070498,0.223684,0.026356,0.365634
6,(Game),(Headset),0.3600,0.3450,0.1250,0.347222,1.006441,1.0,0.000800,1.003404,0.010000,0.215517,0.003393,0.354771
7,(Headset),(Game),0.3450,0.3600,0.1250,0.362319,1.006441,1.0,0.000800,1.003636,0.009771,0.215517,0.003623,0.354771
8,(Headset),(Game Pass),0.3450,0.3225,0.1125,0.326087,1.011122,1.0,0.001238,1.005323,0.016794,0.202703,0.005294,0.337462
9,(Game Pass),(Headset),0.3225,0.3450,0.1125,0.348837,1.011122,1.0,0.001238,1.005893,0.016236,0.202703,0.005858,0.337462
10,(Headset),(Gift Card),0.3450,0.3975,0.1400,0.405797,1.020873,1.0,0.002863,1.013963,0.031216,0.232365,0.013771,0.378999
11,(Gift Card),(Headset),0.3975,0.3450,0.1400,0.352201,1.020873,1.0,0.002863,1.011117,0.033936,0.232365,0.010994,0.378999

The association rule analysis identified several meaningful purchasing patternsw ithin the Gamestore dataset. The strongest rule was Batteries -> Gift Card, with a support of 0.16, confidence of 0.438, and lift of 1.103. This means that 16% of all transactions contained both items, and when Batteries were purchaced, there was a 43.8% chance that a Gift Card was also included. The lieft value greater than 1 indicated a positive relationship, meaning customers who buy Batteries are about 10% more likely to also purchase a Gift Card compared to random chance. Other notable patterns include Console -> Controller (confidence around 39.7%) and Console -> Headset (confidence around 36.2%), suggesting that accessories are commonly purchased alongside consoles.

Overall, the lift values across the rules are slightly above 1, which confirms positive but moderate associations between products. While the relationships are not extremely strong, they stulle provide useful business insight. These patterns suggest opportunities for bundling consoles with controllers or headset, recommending batteries with related accessories, and strategically placing complementary products near each other in-store or online. Leveraging these associations could help increase average transaction value and improve cross-selling effectiveness.